<?php
$SERVER_RECEIVE_TRANSFER_KEY = ""; //SERVER_SEND_TRANSFER_KEY on the client
$SERVER_SEND_TRANSFER_KEY = ""; //SERVER_RECEIVE_TRANSFER_KEY on the client
$SERVER_RECEIVE_TRANSFER_KEY_SPECIFIC = [];
$SERVER_SEND_TRANSFER_KEY_SPECIFIC = [];